// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type TradePair struct {
	ID         int64     `db:"id" json:"id"`
	TraderID   int64     `db:"trader_id" json:"trader_id"`
	BaseAsset  string    `db:"base_asset" json:"base_asset"`
	QuoteAsset string    `db:"quote_asset" json:"quote_asset"`
	BuyRate    float64   `db:"buy_rate" json:"buy_rate"`
	SellRate   float64   `db:"sell_rate" json:"sell_rate"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type Trader struct {
	ID         int64          `db:"id" json:"id"`
	FirstName  string         `db:"first_name" json:"first_name"`
	LastName   string         `db:"last_name" json:"last_name"`
	Username   string         `db:"username" json:"username"`
	Password   string         `db:"password" json:"password"`
	Email      string         `db:"email" json:"email"`
	Country    string         `db:"country" json:"country"`
	Phone      string         `db:"phone" json:"phone"`
	Role       string         `db:"role" json:"role"`
	ProfilePic sql.NullString `db:"profile_pic" json:"profile_pic"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	IsVerified bool           `db:"isVerified" json:"isVerified"`
}

type VerifyEmail struct {
	ID         int64     `db:"id" json:"id"`
	Username   string    `db:"username" json:"username"`
	Email      string    `db:"email" json:"email"`
	SecretCode string    `db:"secret_code" json:"secret_code"`
	IsUsed     bool      `db:"is_used" json:"is_used"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	ExpiredAt  time.Time `db:"expired_at" json:"expired_at"`
}
