// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID            int64     `db:"id" json:"id"`
	Username      string    `db:"username" json:"username"`
	EscrowAddress string    `db:"escrow_address" json:"escrow_address"`
	UserAddress   string    `db:"user_address" json:"user_address"`
	OrderType     string    `db:"order_type" json:"order_type"`
	Crypto        string    `db:"crypto" json:"crypto"`
	Fiat          string    `db:"fiat" json:"fiat"`
	CryptoAmount  float64   `db:"crypto_amount" json:"crypto_amount"`
	FiatAmount    float64   `db:"fiat_amount" json:"fiat_amount"`
	Rate          float64   `db:"rate" json:"rate"`
	IsAccepted    bool      `db:"is_accepted" json:"is_accepted"`
	IsCompleted   bool      `db:"is_completed" json:"is_completed"`
	IsRejected    bool      `db:"is_rejected" json:"is_rejected"`
	IsExpired     bool      `db:"is_expired" json:"is_expired"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	Duration      time.Time `db:"duration" json:"duration"`
}

type PaymentMethod struct {
	ID            int64     `db:"id" json:"id"`
	TradePairID   int64     `db:"trade_pair_id" json:"trade_pair_id"`
	Username      string    `db:"username" json:"username"`
	WalletAddress string    `db:"wallet_address" json:"wallet_address"`
	Crypto        string    `db:"crypto" json:"crypto"`
	Fiat          string    `db:"fiat" json:"fiat"`
	BankName      string    `db:"bank_name" json:"bank_name"`
	AccountNumber string    `db:"account_number" json:"account_number"`
	AccountHolder string    `db:"account_holder" json:"account_holder"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `db:"id" json:"id"`
	TraderID     int64     `db:"trader_id" json:"trader_id"`
	Username     string    `db:"username" json:"username"`
	RefreshToken string    `db:"refresh_token" json:"refresh_token"`
	UserAgent    string    `db:"user_agent" json:"user_agent"`
	ClientIp     string    `db:"client_ip" json:"client_ip"`
	IsBlocked    bool      `db:"is_blocked" json:"is_blocked"`
	ExpiredAt    time.Time `db:"expired_at" json:"expired_at"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type TradePair struct {
	ID        int64     `db:"id" json:"id"`
	Username  string    `db:"username" json:"username"`
	Crypto    string    `db:"crypto" json:"crypto"`
	Fiat      string    `db:"fiat" json:"fiat"`
	BuyRate   float64   `db:"buy_rate" json:"buy_rate"`
	SellRate  float64   `db:"sell_rate" json:"sell_rate"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Trader struct {
	ID               int64          `db:"id" json:"id"`
	FirstName        string         `db:"first_name" json:"first_name"`
	LastName         string         `db:"last_name" json:"last_name"`
	Username         string         `db:"username" json:"username"`
	Password         string         `db:"password" json:"password"`
	Email            string         `db:"email" json:"email"`
	IsVerified       bool           `db:"is_verified" json:"is_verified"`
	VerificationCode string         `db:"verification_code" json:"verification_code"`
	Country          string         `db:"country" json:"country"`
	Phone            string         `db:"phone" json:"phone"`
	Role             string         `db:"role" json:"role"`
	ProfilePic       sql.NullString `db:"profile_pic" json:"profile_pic"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
}
