// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateTradePair(ctx context.Context, arg CreateTradePairParams) (TradePair, error)
	CreateTrader(ctx context.Context, arg CreateTraderParams) (Trader, error)
}

var _ Querier = (*Queries)(nil)
