// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trade_pair.sql

package db

import (
	"context"
)

const createTradePair = `-- name: CreateTradePair :one
INSERT INTO trade_pairs (
  trader_id, base_asset, quote_asset, buy_rate, sell_rate
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, trader_id, base_asset, quote_asset, buy_rate, sell_rate, created_at
`

type CreateTradePairParams struct {
	TraderID   int64  `db:"trader_id" json:"trader_id"`
	BaseAsset  string `db:"base_asset" json:"base_asset"`
	QuoteAsset string `db:"quote_asset" json:"quote_asset"`
	BuyRate    string `db:"buy_rate" json:"buy_rate"`
	SellRate   string `db:"sell_rate" json:"sell_rate"`
}

func (q *Queries) CreateTradePair(ctx context.Context, arg CreateTradePairParams) (TradePair, error) {
	row := q.db.QueryRowContext(ctx, createTradePair,
		arg.TraderID,
		arg.BaseAsset,
		arg.QuoteAsset,
		arg.BuyRate,
		arg.SellRate,
	)
	var i TradePair
	err := row.Scan(
		&i.ID,
		&i.TraderID,
		&i.BaseAsset,
		&i.QuoteAsset,
		&i.BuyRate,
		&i.SellRate,
		&i.CreatedAt,
	)
	return i, err
}
