// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: peerbill-trader.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PeerBillTraderClient is the client API for PeerBillTrader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerBillTraderClient interface {
	CreateTrader(ctx context.Context, in *CreateTraderRequest, opts ...grpc.CallOption) (*CreateTraderResponse, error)
	LoginTrader(ctx context.Context, in *LoginTraderRequest, opts ...grpc.CallOption) (*LoginTraderResponse, error)
}

type peerBillTraderClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerBillTraderClient(cc grpc.ClientConnInterface) PeerBillTraderClient {
	return &peerBillTraderClient{cc}
}

func (c *peerBillTraderClient) CreateTrader(ctx context.Context, in *CreateTraderRequest, opts ...grpc.CallOption) (*CreateTraderResponse, error) {
	out := new(CreateTraderResponse)
	err := c.cc.Invoke(ctx, "/pb.PeerBillTrader/CreateTrader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerBillTraderClient) LoginTrader(ctx context.Context, in *LoginTraderRequest, opts ...grpc.CallOption) (*LoginTraderResponse, error) {
	out := new(LoginTraderResponse)
	err := c.cc.Invoke(ctx, "/pb.PeerBillTrader/LoginTrader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerBillTraderServer is the server API for PeerBillTrader service.
// All implementations must embed UnimplementedPeerBillTraderServer
// for forward compatibility
type PeerBillTraderServer interface {
	CreateTrader(context.Context, *CreateTraderRequest) (*CreateTraderResponse, error)
	LoginTrader(context.Context, *LoginTraderRequest) (*LoginTraderResponse, error)
	mustEmbedUnimplementedPeerBillTraderServer()
}

// UnimplementedPeerBillTraderServer must be embedded to have forward compatible implementations.
type UnimplementedPeerBillTraderServer struct {
}

func (UnimplementedPeerBillTraderServer) CreateTrader(context.Context, *CreateTraderRequest) (*CreateTraderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrader not implemented")
}
func (UnimplementedPeerBillTraderServer) LoginTrader(context.Context, *LoginTraderRequest) (*LoginTraderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginTrader not implemented")
}
func (UnimplementedPeerBillTraderServer) mustEmbedUnimplementedPeerBillTraderServer() {}

// UnsafePeerBillTraderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerBillTraderServer will
// result in compilation errors.
type UnsafePeerBillTraderServer interface {
	mustEmbedUnimplementedPeerBillTraderServer()
}

func RegisterPeerBillTraderServer(s grpc.ServiceRegistrar, srv PeerBillTraderServer) {
	s.RegisterService(&PeerBillTrader_ServiceDesc, srv)
}

func _PeerBillTrader_CreateTrader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTraderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBillTraderServer).CreateTrader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PeerBillTrader/CreateTrader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBillTraderServer).CreateTrader(ctx, req.(*CreateTraderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerBillTrader_LoginTrader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginTraderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBillTraderServer).LoginTrader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PeerBillTrader/LoginTrader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBillTraderServer).LoginTrader(ctx, req.(*LoginTraderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerBillTrader_ServiceDesc is the grpc.ServiceDesc for PeerBillTrader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerBillTrader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PeerBillTrader",
	HandlerType: (*PeerBillTraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrader",
			Handler:    _PeerBillTrader_CreateTrader_Handler,
		},
		{
			MethodName: "LoginTrader",
			Handler:    _PeerBillTrader_LoginTrader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peerbill-trader.proto",
}
