// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: peerbill_trader.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerbillTrader_RegisterTrader_FullMethodName      = "/pb.PeerbillTrader/RegisterTrader"
	PeerbillTrader_LoginTrader_FullMethodName         = "/pb.PeerbillTrader/LoginTrader"
	PeerbillTrader_LogoutTrader_FullMethodName        = "/pb.PeerbillTrader/LogoutTrader"
	PeerbillTrader_UpdateTrader_FullMethodName        = "/pb.PeerbillTrader/UpdateTrader"
	PeerbillTrader_VerifyEmail_FullMethodName         = "/pb.PeerbillTrader/VerifyEmail"
	PeerbillTrader_Forgot_FullMethodName              = "/pb.PeerbillTrader/Forgot"
	PeerbillTrader_Reset_FullMethodName               = "/pb.PeerbillTrader/Reset"
	PeerbillTrader_GetTraders_FullMethodName          = "/pb.PeerbillTrader/GetTraders"
	PeerbillTrader_AddTraderPair_FullMethodName       = "/pb.PeerbillTrader/AddTraderPair"
	PeerbillTrader_UpdateTraderPair_FullMethodName    = "/pb.PeerbillTrader/UpdateTraderPair"
	PeerbillTrader_DeleteTraderPair_FullMethodName    = "/pb.PeerbillTrader/DeleteTraderPair"
	PeerbillTrader_CreateOrder_FullMethodName         = "/pb.PeerbillTrader/CreateOrder"
	PeerbillTrader_GetOrders_FullMethodName           = "/pb.PeerbillTrader/GetOrders"
	PeerbillTrader_GetUserOrders_FullMethodName       = "/pb.PeerbillTrader/GetUserOrders"
	PeerbillTrader_GetOrder_FullMethodName            = "/pb.PeerbillTrader/GetOrder"
	PeerbillTrader_AcceptOrder_FullMethodName         = "/pb.PeerbillTrader/AcceptOrder"
	PeerbillTrader_RejectOrder_FullMethodName         = "/pb.PeerbillTrader/RejectOrder"
	PeerbillTrader_AddPaymentMethod_FullMethodName    = "/pb.PeerbillTrader/AddPaymentMethod"
	PeerbillTrader_UpdatePaymentMethod_FullMethodName = "/pb.PeerbillTrader/UpdatePaymentMethod"
	PeerbillTrader_DeletePaymentMethod_FullMethodName = "/pb.PeerbillTrader/DeletePaymentMethod"
	PeerbillTrader_GetPaymentMethod_FullMethodName    = "/pb.PeerbillTrader/GetPaymentMethod"
	PeerbillTrader_ReceivePayment_FullMethodName      = "/pb.PeerbillTrader/ReceivePayment"
	PeerbillTrader_MadePayment_FullMethodName         = "/pb.PeerbillTrader/MadePayment"
)

// PeerbillTraderClient is the client API for PeerbillTrader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerbillTraderClient interface {
	RegisterTrader(ctx context.Context, in *RegisterTraderRequest, opts ...grpc.CallOption) (*RegisterTraderResponse, error)
	LoginTrader(ctx context.Context, in *LoginTraderRequest, opts ...grpc.CallOption) (*LoginTraderResponse, error)
	LogoutTrader(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	UpdateTrader(ctx context.Context, in *UpdateTraderRequest, opts ...grpc.CallOption) (*UpdateTraderResponse, error)
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
	Forgot(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	Reset(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	GetTraders(ctx context.Context, in *GetTradersRequest, opts ...grpc.CallOption) (*GetTradersResponse, error)
	AddTraderPair(ctx context.Context, in *AddTradePairRequest, opts ...grpc.CallOption) (*AddTradePairResponse, error)
	UpdateTraderPair(ctx context.Context, in *UpdateTradePairRequest, opts ...grpc.CallOption) (*UpdateTradePairResponse, error)
	DeleteTraderPair(ctx context.Context, in *DeleteTradePairRequest, opts ...grpc.CallOption) (*DeleteTradePairResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*GetUserOrdersResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error)
	RejectOrder(ctx context.Context, in *RejectOrderRequest, opts ...grpc.CallOption) (*RejectOrderResponse, error)
	AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error)
	UpdatePaymentMethod(ctx context.Context, in *UpdatePaymentMethodRequest, opts ...grpc.CallOption) (*UpdatePaymentMethodResponse, error)
	DeletePaymentMethod(ctx context.Context, in *DeletePaymentMethodRequest, opts ...grpc.CallOption) (*DeletePaymentMethodResponse, error)
	GetPaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*GetPaymentMethodResponse, error)
	ReceivePayment(ctx context.Context, in *ReceivedPaymentRequest, opts ...grpc.CallOption) (*ReceivedPaymentResponse, error)
	MadePayment(ctx context.Context, in *MadePaymentRequest, opts ...grpc.CallOption) (*MadePaymentResponse, error)
}

type peerbillTraderClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerbillTraderClient(cc grpc.ClientConnInterface) PeerbillTraderClient {
	return &peerbillTraderClient{cc}
}

func (c *peerbillTraderClient) RegisterTrader(ctx context.Context, in *RegisterTraderRequest, opts ...grpc.CallOption) (*RegisterTraderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTraderResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_RegisterTrader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) LoginTrader(ctx context.Context, in *LoginTraderRequest, opts ...grpc.CallOption) (*LoginTraderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginTraderResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_LoginTrader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) LogoutTrader(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_LogoutTrader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) UpdateTrader(ctx context.Context, in *UpdateTraderRequest, opts ...grpc.CallOption) (*UpdateTraderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTraderResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_UpdateTrader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) Forgot(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_Forgot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) Reset(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) GetTraders(ctx context.Context, in *GetTradersRequest, opts ...grpc.CallOption) (*GetTradersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradersResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_GetTraders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) AddTraderPair(ctx context.Context, in *AddTradePairRequest, opts ...grpc.CallOption) (*AddTradePairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTradePairResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_AddTraderPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) UpdateTraderPair(ctx context.Context, in *UpdateTradePairRequest, opts ...grpc.CallOption) (*UpdateTradePairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTradePairResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_UpdateTraderPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) DeleteTraderPair(ctx context.Context, in *DeleteTradePairRequest, opts ...grpc.CallOption) (*DeleteTradePairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTradePairResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_DeleteTraderPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_GetOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*GetUserOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserOrdersResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_GetUserOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOrderResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) RejectOrder(ctx context.Context, in *RejectOrderRequest, opts ...grpc.CallOption) (*RejectOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectOrderResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_RejectOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPaymentMethodResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_AddPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) UpdatePaymentMethod(ctx context.Context, in *UpdatePaymentMethodRequest, opts ...grpc.CallOption) (*UpdatePaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePaymentMethodResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_UpdatePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) DeletePaymentMethod(ctx context.Context, in *DeletePaymentMethodRequest, opts ...grpc.CallOption) (*DeletePaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePaymentMethodResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_DeletePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) GetPaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*GetPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentMethodResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_GetPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) ReceivePayment(ctx context.Context, in *ReceivedPaymentRequest, opts ...grpc.CallOption) (*ReceivedPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceivedPaymentResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_ReceivePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerbillTraderClient) MadePayment(ctx context.Context, in *MadePaymentRequest, opts ...grpc.CallOption) (*MadePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MadePaymentResponse)
	err := c.cc.Invoke(ctx, PeerbillTrader_MadePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerbillTraderServer is the server API for PeerbillTrader service.
// All implementations must embed UnimplementedPeerbillTraderServer
// for forward compatibility.
type PeerbillTraderServer interface {
	RegisterTrader(context.Context, *RegisterTraderRequest) (*RegisterTraderResponse, error)
	LoginTrader(context.Context, *LoginTraderRequest) (*LoginTraderResponse, error)
	LogoutTrader(context.Context, *LogoutRequest) (*LogoutResponse, error)
	UpdateTrader(context.Context, *UpdateTraderRequest) (*UpdateTraderResponse, error)
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	Forgot(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	Reset(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	GetTraders(context.Context, *GetTradersRequest) (*GetTradersResponse, error)
	AddTraderPair(context.Context, *AddTradePairRequest) (*AddTradePairResponse, error)
	UpdateTraderPair(context.Context, *UpdateTradePairRequest) (*UpdateTradePairResponse, error)
	DeleteTraderPair(context.Context, *DeleteTradePairRequest) (*DeleteTradePairResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error)
	GetUserOrders(context.Context, *GetUserOrdersRequest) (*GetUserOrdersResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error)
	RejectOrder(context.Context, *RejectOrderRequest) (*RejectOrderResponse, error)
	AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error)
	UpdatePaymentMethod(context.Context, *UpdatePaymentMethodRequest) (*UpdatePaymentMethodResponse, error)
	DeletePaymentMethod(context.Context, *DeletePaymentMethodRequest) (*DeletePaymentMethodResponse, error)
	GetPaymentMethod(context.Context, *GetPaymentMethodRequest) (*GetPaymentMethodResponse, error)
	ReceivePayment(context.Context, *ReceivedPaymentRequest) (*ReceivedPaymentResponse, error)
	MadePayment(context.Context, *MadePaymentRequest) (*MadePaymentResponse, error)
	mustEmbedUnimplementedPeerbillTraderServer()
}

// UnimplementedPeerbillTraderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerbillTraderServer struct{}

func (UnimplementedPeerbillTraderServer) RegisterTrader(context.Context, *RegisterTraderRequest) (*RegisterTraderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTrader not implemented")
}
func (UnimplementedPeerbillTraderServer) LoginTrader(context.Context, *LoginTraderRequest) (*LoginTraderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginTrader not implemented")
}
func (UnimplementedPeerbillTraderServer) LogoutTrader(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogoutTrader not implemented")
}
func (UnimplementedPeerbillTraderServer) UpdateTrader(context.Context, *UpdateTraderRequest) (*UpdateTraderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrader not implemented")
}
func (UnimplementedPeerbillTraderServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedPeerbillTraderServer) Forgot(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forgot not implemented")
}
func (UnimplementedPeerbillTraderServer) Reset(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedPeerbillTraderServer) GetTraders(context.Context, *GetTradersRequest) (*GetTradersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTraders not implemented")
}
func (UnimplementedPeerbillTraderServer) AddTraderPair(context.Context, *AddTradePairRequest) (*AddTradePairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTraderPair not implemented")
}
func (UnimplementedPeerbillTraderServer) UpdateTraderPair(context.Context, *UpdateTradePairRequest) (*UpdateTradePairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTraderPair not implemented")
}
func (UnimplementedPeerbillTraderServer) DeleteTraderPair(context.Context, *DeleteTradePairRequest) (*DeleteTradePairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTraderPair not implemented")
}
func (UnimplementedPeerbillTraderServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedPeerbillTraderServer) GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}
func (UnimplementedPeerbillTraderServer) GetUserOrders(context.Context, *GetUserOrdersRequest) (*GetUserOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrders not implemented")
}
func (UnimplementedPeerbillTraderServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedPeerbillTraderServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedPeerbillTraderServer) RejectOrder(context.Context, *RejectOrderRequest) (*RejectOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectOrder not implemented")
}
func (UnimplementedPeerbillTraderServer) AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPaymentMethod not implemented")
}
func (UnimplementedPeerbillTraderServer) UpdatePaymentMethod(context.Context, *UpdatePaymentMethodRequest) (*UpdatePaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaymentMethod not implemented")
}
func (UnimplementedPeerbillTraderServer) DeletePaymentMethod(context.Context, *DeletePaymentMethodRequest) (*DeletePaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePaymentMethod not implemented")
}
func (UnimplementedPeerbillTraderServer) GetPaymentMethod(context.Context, *GetPaymentMethodRequest) (*GetPaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethod not implemented")
}
func (UnimplementedPeerbillTraderServer) ReceivePayment(context.Context, *ReceivedPaymentRequest) (*ReceivedPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceivePayment not implemented")
}
func (UnimplementedPeerbillTraderServer) MadePayment(context.Context, *MadePaymentRequest) (*MadePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MadePayment not implemented")
}
func (UnimplementedPeerbillTraderServer) mustEmbedUnimplementedPeerbillTraderServer() {}
func (UnimplementedPeerbillTraderServer) testEmbeddedByValue()                        {}

// UnsafePeerbillTraderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerbillTraderServer will
// result in compilation errors.
type UnsafePeerbillTraderServer interface {
	mustEmbedUnimplementedPeerbillTraderServer()
}

func RegisterPeerbillTraderServer(s grpc.ServiceRegistrar, srv PeerbillTraderServer) {
	// If the following call pancis, it indicates UnimplementedPeerbillTraderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerbillTrader_ServiceDesc, srv)
}

func _PeerbillTrader_RegisterTrader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTraderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).RegisterTrader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_RegisterTrader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).RegisterTrader(ctx, req.(*RegisterTraderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_LoginTrader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginTraderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).LoginTrader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_LoginTrader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).LoginTrader(ctx, req.(*LoginTraderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_LogoutTrader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).LogoutTrader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_LogoutTrader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).LogoutTrader(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_UpdateTrader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTraderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).UpdateTrader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_UpdateTrader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).UpdateTrader(ctx, req.(*UpdateTraderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_Forgot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).Forgot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_Forgot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).Forgot(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).Reset(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_GetTraders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).GetTraders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_GetTraders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).GetTraders(ctx, req.(*GetTradersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_AddTraderPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTradePairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).AddTraderPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_AddTraderPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).AddTraderPair(ctx, req.(*AddTradePairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_UpdateTraderPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTradePairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).UpdateTraderPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_UpdateTraderPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).UpdateTraderPair(ctx, req.(*UpdateTradePairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_DeleteTraderPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTradePairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).DeleteTraderPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_DeleteTraderPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).DeleteTraderPair(ctx, req.(*DeleteTradePairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_GetOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_GetUserOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).GetUserOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_GetUserOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).GetUserOrders(ctx, req.(*GetUserOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).AcceptOrder(ctx, req.(*AcceptOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_RejectOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).RejectOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_RejectOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).RejectOrder(ctx, req.(*RejectOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_AddPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).AddPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_AddPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).AddPaymentMethod(ctx, req.(*AddPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_UpdatePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).UpdatePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_UpdatePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).UpdatePaymentMethod(ctx, req.(*UpdatePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_DeletePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).DeletePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_DeletePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).DeletePaymentMethod(ctx, req.(*DeletePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_GetPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).GetPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_GetPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).GetPaymentMethod(ctx, req.(*GetPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_ReceivePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceivedPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).ReceivePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_ReceivePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).ReceivePayment(ctx, req.(*ReceivedPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerbillTrader_MadePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MadePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerbillTraderServer).MadePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerbillTrader_MadePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerbillTraderServer).MadePayment(ctx, req.(*MadePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerbillTrader_ServiceDesc is the grpc.ServiceDesc for PeerbillTrader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerbillTrader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PeerbillTrader",
	HandlerType: (*PeerbillTraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTrader",
			Handler:    _PeerbillTrader_RegisterTrader_Handler,
		},
		{
			MethodName: "LoginTrader",
			Handler:    _PeerbillTrader_LoginTrader_Handler,
		},
		{
			MethodName: "LogoutTrader",
			Handler:    _PeerbillTrader_LogoutTrader_Handler,
		},
		{
			MethodName: "UpdateTrader",
			Handler:    _PeerbillTrader_UpdateTrader_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _PeerbillTrader_VerifyEmail_Handler,
		},
		{
			MethodName: "Forgot",
			Handler:    _PeerbillTrader_Forgot_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _PeerbillTrader_Reset_Handler,
		},
		{
			MethodName: "GetTraders",
			Handler:    _PeerbillTrader_GetTraders_Handler,
		},
		{
			MethodName: "AddTraderPair",
			Handler:    _PeerbillTrader_AddTraderPair_Handler,
		},
		{
			MethodName: "UpdateTraderPair",
			Handler:    _PeerbillTrader_UpdateTraderPair_Handler,
		},
		{
			MethodName: "DeleteTraderPair",
			Handler:    _PeerbillTrader_DeleteTraderPair_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _PeerbillTrader_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _PeerbillTrader_GetOrders_Handler,
		},
		{
			MethodName: "GetUserOrders",
			Handler:    _PeerbillTrader_GetUserOrders_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _PeerbillTrader_GetOrder_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _PeerbillTrader_AcceptOrder_Handler,
		},
		{
			MethodName: "RejectOrder",
			Handler:    _PeerbillTrader_RejectOrder_Handler,
		},
		{
			MethodName: "AddPaymentMethod",
			Handler:    _PeerbillTrader_AddPaymentMethod_Handler,
		},
		{
			MethodName: "UpdatePaymentMethod",
			Handler:    _PeerbillTrader_UpdatePaymentMethod_Handler,
		},
		{
			MethodName: "DeletePaymentMethod",
			Handler:    _PeerbillTrader_DeletePaymentMethod_Handler,
		},
		{
			MethodName: "GetPaymentMethod",
			Handler:    _PeerbillTrader_GetPaymentMethod_Handler,
		},
		{
			MethodName: "ReceivePayment",
			Handler:    _PeerbillTrader_ReceivePayment_Handler,
		},
		{
			MethodName: "MadePayment",
			Handler:    _PeerbillTrader_MadePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peerbill_trader.proto",
}
