// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: rpc_add_payment_method.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPaymentMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Crypto        string `protobuf:"bytes,2,opt,name=crypto,proto3" json:"crypto,omitempty"`
	Fiat          string `protobuf:"bytes,3,opt,name=fiat,proto3" json:"fiat,omitempty"`
	BankName      string `protobuf:"bytes,4,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	AccountHolder string `protobuf:"bytes,5,opt,name=account_holder,json=accountHolder,proto3" json:"account_holder,omitempty"`
	AccountNumber string `protobuf:"bytes,6,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	WalletAddress string `protobuf:"bytes,7,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
}

func (x *AddPaymentMethodRequest) Reset() {
	*x = AddPaymentMethodRequest{}
	mi := &file_rpc_add_payment_method_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentMethodRequest) ProtoMessage() {}

func (x *AddPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_payment_method_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*AddPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_rpc_add_payment_method_proto_rawDescGZIP(), []int{0}
}

func (x *AddPaymentMethodRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetCrypto() string {
	if x != nil {
		return x.Crypto
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetFiat() string {
	if x != nil {
		return x.Fiat
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetAccountHolder() string {
	if x != nil {
		return x.AccountHolder
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type AddPaymentMethodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentMethods []*PaymentMethod `protobuf:"bytes,1,rep,name=paymentMethods,proto3" json:"paymentMethods,omitempty"`
}

func (x *AddPaymentMethodResponse) Reset() {
	*x = AddPaymentMethodResponse{}
	mi := &file_rpc_add_payment_method_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentMethodResponse) ProtoMessage() {}

func (x *AddPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_payment_method_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*AddPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_rpc_add_payment_method_proto_rawDescGZIP(), []int{1}
}

func (x *AddPaymentMethodResponse) GetPaymentMethods() []*PaymentMethod {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

var File_rpc_add_payment_method_proto protoreflect.FileDescriptor

var file_rpc_add_payment_method_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x14, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x17, 0x41, 0x64, 0x64,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x55,
	0x0a, 0x18, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x62, 0x75, 0x6b, 0x61, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x31,
	0x2f, 0x70, 0x65, 0x65, 0x72, 0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_add_payment_method_proto_rawDescOnce sync.Once
	file_rpc_add_payment_method_proto_rawDescData = file_rpc_add_payment_method_proto_rawDesc
)

func file_rpc_add_payment_method_proto_rawDescGZIP() []byte {
	file_rpc_add_payment_method_proto_rawDescOnce.Do(func() {
		file_rpc_add_payment_method_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_add_payment_method_proto_rawDescData)
	})
	return file_rpc_add_payment_method_proto_rawDescData
}

var file_rpc_add_payment_method_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_add_payment_method_proto_goTypes = []any{
	(*AddPaymentMethodRequest)(nil),  // 0: pb.AddPaymentMethodRequest
	(*AddPaymentMethodResponse)(nil), // 1: pb.AddPaymentMethodResponse
	(*PaymentMethod)(nil),            // 2: pb.PaymentMethod
}
var file_rpc_add_payment_method_proto_depIdxs = []int32{
	2, // 0: pb.AddPaymentMethodResponse.paymentMethods:type_name -> pb.PaymentMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_add_payment_method_proto_init() }
func file_rpc_add_payment_method_proto_init() {
	if File_rpc_add_payment_method_proto != nil {
		return
	}
	file_payment_method_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_add_payment_method_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_add_payment_method_proto_goTypes,
		DependencyIndexes: file_rpc_add_payment_method_proto_depIdxs,
		MessageInfos:      file_rpc_add_payment_method_proto_msgTypes,
	}.Build()
	File_rpc_add_payment_method_proto = out.File
	file_rpc_add_payment_method_proto_rawDesc = nil
	file_rpc_add_payment_method_proto_goTypes = nil
	file_rpc_add_payment_method_proto_depIdxs = nil
}
