// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: rpc_receive_payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceivedPaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	OrderType       string `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	ReceivedPayment bool   `protobuf:"varint,4,opt,name=received_payment,json=receivedPayment,proto3" json:"received_payment,omitempty"`
}

func (x *ReceivedPaymentRequest) Reset() {
	*x = ReceivedPaymentRequest{}
	mi := &file_rpc_receive_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedPaymentRequest) ProtoMessage() {}

func (x *ReceivedPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receive_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedPaymentRequest.ProtoReflect.Descriptor instead.
func (*ReceivedPaymentRequest) Descriptor() ([]byte, []int) {
	return file_rpc_receive_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ReceivedPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReceivedPaymentRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReceivedPaymentRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *ReceivedPaymentRequest) GetReceivedPayment() bool {
	if x != nil {
		return x.ReceivedPayment
	}
	return false
}

type ReceivedPaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *ReceivedPaymentResponse) Reset() {
	*x = ReceivedPaymentResponse{}
	mi := &file_rpc_receive_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedPaymentResponse) ProtoMessage() {}

func (x *ReceivedPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receive_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedPaymentResponse.ProtoReflect.Descriptor instead.
func (*ReceivedPaymentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_receive_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ReceivedPaymentResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_rpc_receive_payment_proto protoreflect.FileDescriptor

var file_rpc_receive_payment_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a,
	0x16, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3c, 0x0a,
	0x17, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x62, 0x75, 0x6b, 0x61, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x32, 0x31, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x62, 0x69, 0x6c, 0x6c, 0x2d,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_receive_payment_proto_rawDescOnce sync.Once
	file_rpc_receive_payment_proto_rawDescData = file_rpc_receive_payment_proto_rawDesc
)

func file_rpc_receive_payment_proto_rawDescGZIP() []byte {
	file_rpc_receive_payment_proto_rawDescOnce.Do(func() {
		file_rpc_receive_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_receive_payment_proto_rawDescData)
	})
	return file_rpc_receive_payment_proto_rawDescData
}

var file_rpc_receive_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_receive_payment_proto_goTypes = []any{
	(*ReceivedPaymentRequest)(nil),  // 0: pb.ReceivedPaymentRequest
	(*ReceivedPaymentResponse)(nil), // 1: pb.ReceivedPaymentResponse
	(*Order)(nil),                   // 2: pb.Order
}
var file_rpc_receive_payment_proto_depIdxs = []int32{
	2, // 0: pb.ReceivedPaymentResponse.orders:type_name -> pb.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_receive_payment_proto_init() }
func file_rpc_receive_payment_proto_init() {
	if File_rpc_receive_payment_proto != nil {
		return
	}
	file_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_receive_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_receive_payment_proto_goTypes,
		DependencyIndexes: file_rpc_receive_payment_proto_depIdxs,
		MessageInfos:      file_rpc_receive_payment_proto_msgTypes,
	}.Build()
	File_rpc_receive_payment_proto = out.File
	file_rpc_receive_payment_proto_rawDesc = nil
	file_rpc_receive_payment_proto_goTypes = nil
	file_rpc_receive_payment_proto_depIdxs = nil
}
