// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: rpc_register_trader.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTraderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Country   string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Phone     string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Password  string `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterTraderRequest) Reset() {
	*x = RegisterTraderRequest{}
	mi := &file_rpc_register_trader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTraderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTraderRequest) ProtoMessage() {}

func (x *RegisterTraderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_register_trader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTraderRequest.ProtoReflect.Descriptor instead.
func (*RegisterTraderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_register_trader_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTraderRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterTraderRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterTraderRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterTraderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterTraderRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RegisterTraderRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterTraderRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterTraderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trader *Trader `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
}

func (x *RegisterTraderResponse) Reset() {
	*x = RegisterTraderResponse{}
	mi := &file_rpc_register_trader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTraderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTraderResponse) ProtoMessage() {}

func (x *RegisterTraderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_register_trader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTraderResponse.ProtoReflect.Descriptor instead.
func (*RegisterTraderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_register_trader_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTraderResponse) GetTrader() *Trader {
	if x != nil {
		return x.Trader
	}
	return nil
}

var File_rpc_register_trader_proto protoreflect.FileDescriptor

var file_rpc_register_trader_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x0c, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01,
	0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x3c, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x42,
	0x14, 0x5a, 0x12, 0x70, 0x65, 0x65, 0x72, 0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_register_trader_proto_rawDescOnce sync.Once
	file_rpc_register_trader_proto_rawDescData = file_rpc_register_trader_proto_rawDesc
)

func file_rpc_register_trader_proto_rawDescGZIP() []byte {
	file_rpc_register_trader_proto_rawDescOnce.Do(func() {
		file_rpc_register_trader_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_register_trader_proto_rawDescData)
	})
	return file_rpc_register_trader_proto_rawDescData
}

var file_rpc_register_trader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_register_trader_proto_goTypes = []any{
	(*RegisterTraderRequest)(nil),  // 0: pb.RegisterTraderRequest
	(*RegisterTraderResponse)(nil), // 1: pb.RegisterTraderResponse
	(*Trader)(nil),                 // 2: pb.Trader
}
var file_rpc_register_trader_proto_depIdxs = []int32{
	2, // 0: pb.RegisterTraderResponse.trader:type_name -> pb.Trader
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_register_trader_proto_init() }
func file_rpc_register_trader_proto_init() {
	if File_rpc_register_trader_proto != nil {
		return
	}
	file_trader_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_register_trader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_register_trader_proto_goTypes,
		DependencyIndexes: file_rpc_register_trader_proto_depIdxs,
		MessageInfos:      file_rpc_register_trader_proto_msgTypes,
	}.Build()
	File_rpc_register_trader_proto = out.File
	file_rpc_register_trader_proto_rawDesc = nil
	file_rpc_register_trader_proto_goTypes = nil
	file_rpc_register_trader_proto_depIdxs = nil
}
