// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: rpc_get_buy_order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBuyOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderType string `protobuf:"bytes,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
}

func (x *GetBuyOrderRequest) Reset() {
	*x = GetBuyOrderRequest{}
	mi := &file_rpc_get_buy_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyOrderRequest) ProtoMessage() {}

func (x *GetBuyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_buy_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuyOrderRequest.ProtoReflect.Descriptor instead.
func (*GetBuyOrderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_buy_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetBuyOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBuyOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

type GetBuyOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuyOrder *Order `protobuf:"bytes,1,opt,name=buyOrder,proto3" json:"buyOrder,omitempty"`
}

func (x *GetBuyOrderResponse) Reset() {
	*x = GetBuyOrderResponse{}
	mi := &file_rpc_get_buy_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyOrderResponse) ProtoMessage() {}

func (x *GetBuyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_buy_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuyOrderResponse.ProtoReflect.Descriptor instead.
func (*GetBuyOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_buy_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetBuyOrderResponse) GetBuyOrder() *Order {
	if x != nil {
		return x.BuyOrder
	}
	return nil
}

var File_rpc_get_buy_order_proto protoreflect.FileDescriptor

var file_rpc_get_buy_order_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x75, 0x79, 0x5f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x42, 0x75, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x3c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x75, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x08, 0x62, 0x75, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x18, 0x5a,
	0x16, 0x70, 0x65, 0x65, 0x72, 0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_buy_order_proto_rawDescOnce sync.Once
	file_rpc_get_buy_order_proto_rawDescData = file_rpc_get_buy_order_proto_rawDesc
)

func file_rpc_get_buy_order_proto_rawDescGZIP() []byte {
	file_rpc_get_buy_order_proto_rawDescOnce.Do(func() {
		file_rpc_get_buy_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_buy_order_proto_rawDescData)
	})
	return file_rpc_get_buy_order_proto_rawDescData
}

var file_rpc_get_buy_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_buy_order_proto_goTypes = []any{
	(*GetBuyOrderRequest)(nil),  // 0: pb.GetBuyOrderRequest
	(*GetBuyOrderResponse)(nil), // 1: pb.GetBuyOrderResponse
	(*Order)(nil),               // 2: pb.Order
}
var file_rpc_get_buy_order_proto_depIdxs = []int32{
	2, // 0: pb.GetBuyOrderResponse.buyOrder:type_name -> pb.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_buy_order_proto_init() }
func file_rpc_get_buy_order_proto_init() {
	if File_rpc_get_buy_order_proto != nil {
		return
	}
	file_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_buy_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_buy_order_proto_goTypes,
		DependencyIndexes: file_rpc_get_buy_order_proto_depIdxs,
		MessageInfos:      file_rpc_get_buy_order_proto_msgTypes,
	}.Build()
	File_rpc_get_buy_order_proto = out.File
	file_rpc_get_buy_order_proto_rawDesc = nil
	file_rpc_get_buy_order_proto_goTypes = nil
	file_rpc_get_buy_order_proto_depIdxs = nil
}
