// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: trader_details.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraderWithDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trader    *Trader     `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	TradePair *TraderPair `protobuf:"bytes,2,opt,name=tradePair,proto3" json:"tradePair,omitempty"`
}

func (x *TraderWithDetails) Reset() {
	*x = TraderWithDetails{}
	mi := &file_trader_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraderWithDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraderWithDetails) ProtoMessage() {}

func (x *TraderWithDetails) ProtoReflect() protoreflect.Message {
	mi := &file_trader_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraderWithDetails.ProtoReflect.Descriptor instead.
func (*TraderWithDetails) Descriptor() ([]byte, []int) {
	return file_trader_details_proto_rawDescGZIP(), []int{0}
}

func (x *TraderWithDetails) GetTrader() *Trader {
	if x != nil {
		return x.Trader
	}
	return nil
}

func (x *TraderWithDetails) GetTradePair() *TraderPair {
	if x != nil {
		return x.TradePair
	}
	return nil
}

var File_trader_details_proto protoreflect.FileDescriptor

var file_trader_details_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f,
	0x70, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x11, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x22, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x64, 0x65, 0x50, 0x61, 0x69, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x52, 0x09, 0x74, 0x72, 0x61, 0x64, 0x65, 0x50, 0x61, 0x69,
	0x72, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x62, 0x75, 0x6b, 0x61, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x31, 0x2f, 0x70, 0x65, 0x65,
	0x72, 0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trader_details_proto_rawDescOnce sync.Once
	file_trader_details_proto_rawDescData = file_trader_details_proto_rawDesc
)

func file_trader_details_proto_rawDescGZIP() []byte {
	file_trader_details_proto_rawDescOnce.Do(func() {
		file_trader_details_proto_rawDescData = protoimpl.X.CompressGZIP(file_trader_details_proto_rawDescData)
	})
	return file_trader_details_proto_rawDescData
}

var file_trader_details_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trader_details_proto_goTypes = []any{
	(*TraderWithDetails)(nil), // 0: pb.TraderWithDetails
	(*Trader)(nil),            // 1: pb.Trader
	(*TraderPair)(nil),        // 2: pb.TraderPair
}
var file_trader_details_proto_depIdxs = []int32{
	1, // 0: pb.TraderWithDetails.trader:type_name -> pb.Trader
	2, // 1: pb.TraderWithDetails.tradePair:type_name -> pb.TraderPair
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trader_details_proto_init() }
func file_trader_details_proto_init() {
	if File_trader_details_proto != nil {
		return
	}
	file_trader_proto_init()
	file_trade_pair_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trader_details_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trader_details_proto_goTypes,
		DependencyIndexes: file_trader_details_proto_depIdxs,
		MessageInfos:      file_trader_details_proto_msgTypes,
	}.Build()
	File_trader_details_proto = out.File
	file_trader_details_proto_rawDesc = nil
	file_trader_details_proto_goTypes = nil
	file_trader_details_proto_depIdxs = nil
}
